# TODO-PRM: 1a) ustaw obraz bazowy na odpowiednią wersję osrf/ros
FROM ...:...

RUN apt update
# TODO-PRM: 1a) zainstaluj narzędzia wskazane w skrypcie
...

# entrypoint: domyślny z obrazu bazowego, tj. /bin/bash
